setTimeout(()=>{
    console.log("Hacking wifi ...")
},1000)

try{
    console.log(rahul)
} catch(error){
    console.log(error)
}

setTimeout(()=>{
    console.log("Fetching username ...")
},2000)

setTimeout(()=>{
    console.log("Fetching password ...")
},3000)

// try and catch cannot be applied to scheduled functions as try method runs immediately!!!